# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Built-in hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=500000"]

  # Go formatting and imports
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-fmt

  # Check for spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell

  # Changes tabs to spaces (exclude Go files — Go uses tabs)
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-tabs
        exclude: ".*[.]go"

  # Github workflow actionlint
  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: v1.7.7.23
    hooks:
      - id: actionlint
        additional_dependencies: [pyflakes>=3.0.1,shellcheck-py>=0.9.0.5]
        args: ["--config-file=.github/actionlint.yaml"]

  # mdformat
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        args: ["--wrap=80"]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-frontmatter
